In [1]:
import tensorflow as tf

# Define tensors
tensor1 = tf.constant([5, 3, 7])  # Binary: 101, 011, 111
tensor2 = tf.constant([3, 1, 5])  # Binary: 011, 001, 101

# Bitwise AND operation
result_and = tf.bitwise.bitwise_and(tensor1, tensor2)

print("Result of Bitwise AND Operation:")
print(result_and.numpy())  

Result of Bitwise AND Operation:
[1 1 5]


In [2]:
import tensorflow as tf

# Define tensors
tensor1 = tf.constant([5, 3, 7])  # Binary: 101, 011, 111
tensor2 = tf.constant([3, 1, 5])  # Binary: 011, 001, 101

# Bitwise OR operation
result_or = tf.bitwise.bitwise_or(tensor1, tensor2)

# Bitwise shift left by 2 bits
result_shifted = tf.bitwise.left_shift(result_or, 2)

print("Result of Bitwise OR and Shift Operation:")
print(result_shifted.numpy())  # Output: [40, 28, 120]

Result of Bitwise OR and Shift Operation:
[28 12 28]


In [3]:
import tensorflow as tf

# Define tensors
tensor1 = tf.constant([5, 3, 7])  # Binary: 101, 011, 111
tensor2 = tf.constant([3, 1, 5])  # Binary: 011, 001, 101

# Bitwise XOR operation
result_xor = tf.bitwise.bitwise_xor(tensor1, tensor2)

# Count number of set bits (1s)
count_bits = tf.math.count_nonzero(result_xor, axis=-1)

print("Result of Bitwise XOR and Counting Set Bits:")
print(count_bits.numpy())  # Output: [2, 3, 1]

Result of Bitwise XOR and Counting Set Bits:
3


In [4]:
import tensorflow as tf

# Create a sample tensor
tensor = tf.constant([1, 2, 3, 4, 5], dtype=tf.uint8)

# Invert the bits of the tensor
inverted_tensor = tf.bitwise.invert(tensor)

# Print the original and inverted tensors
print("Original tensor:", tensor.numpy())
print("Inverted tensor:", inverted_tensor.numpy())

Original tensor: [1 2 3 4 5]
Inverted tensor: [254 253 252 251 250]


In [5]:
import tensorflow as tf

# Define a tensor
tensor = tf.constant([5, 3, 7])  # Binary: 101, 011, 111

# Left shift by 1 bit
result_left_shift = tf.bitwise.left_shift(tensor, 1)

print("Result of Left Shift Operation:")
print(result_left_shift.numpy())  # Output: [10  6 14]

# Right shift by 1 bit
result_right_shift = tf.bitwise.right_shift(tensor, 1)

print("\nResult of Right Shift Operation:")
print(result_right_shift.numpy())  # Output: [2 1 3]

Result of Left Shift Operation:
[10  6 14]

Result of Right Shift Operation:
[2 1 3]
