In [1]:
import tensorflow as tf

Tensor broadcasting is a concept of array processing libraries like TensorFlow and NumPy, it allows for implicit element-wise operations between arrays of different shapes.

In [2]:
import tensorflow as tf

T1 = tf.constant([[1, 2, 8],          # Shape: (2, 3)
                   [4, 7, 6]])

T2 = tf.constant([[7, 8, 10]])        # Shape: (1, 3)

# T2 is compatible so broadcasting it to match the size of shape of T1
# Ranks of both the tensors are 2

# Performing arithmetic operation
T3 = T1 + T2
print(T3)

tf.Tensor(
[[ 8 10 18]
 [11 15 16]], shape=(2, 3), dtype=int32)


In [3]:
import tensorflow as tf

# Tensor T1: 
T1 = tf.constant([[1, 2, 3],      #Rank 2 , shape(2,3)  
              [4, 5, 6]])

# Tensor T2: 
T2 = tf.constant([20, 40, 50])    #Rank 1 ,shape(3,)

# Broadcasting T2 to shape (2, 3) to match T1
#arithmetic operation
T3=T1+T2
print(T3)

tf.Tensor(
[[21 42 53]
 [24 45 56]], shape=(2, 3), dtype=int32)


In [4]:
import tensorflow as tf
T1 =tf.constant([[1, 2, 3],      # Rank 2 , shape (2,3)
              [4, 5, 8]])
T2 =tf.constant (20)           # Rank 0 , shape()
#arithmetic operation
T3 =T1+T2
print(T3)

tf.Tensor(
[[21 22 23]
 [24 25 28]], shape=(2, 3), dtype=int32)


In [5]:
import tensorflow as tf

# tensor T1
T1 =tf. constant([[[10, 11],   #Rank 3 and shape(2,3,2)
                   [20, 20],
                   [30, 30]],
              
                 [ [40, 41],
                   [50, 50],
                   [60, 60]   ]])

# tensor T2
T2= tf.constant([[1, 2, 3],    # Rank 2 and shape (2,3)
                 [4, 5, 6]])

#Adding new axis to T2 by .expand_dims() at its trailing end
broadcasted_T2 = tf.expand_dims(T2, axis=-1)

# arithmetic operation
T3=broadcasted_T2+ T1
print(T3)

tf.Tensor(
[[[11 12]
  [22 22]
  [33 33]]

 [[44 45]
  [55 55]
  [66 66]]], shape=(2, 3, 2), dtype=int32)


In [13]:
t1 = tf.constant([3,4,5,6])
t2 = tf.constant([30,40,50,60])

t1+t2

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([33, 44, 55, 66], dtype=int32)>