In [1]:
import tensorflow as tf
a = tf.constant([3, 3, 3])
b = tf.constant([2, 2, 2])  # Define tensors

sum_result = tf.add(a, b) # Addition
diff_result = tf.subtract(a, b) # Subtraction
quot_result = tf.divide(a, b) # Division
prod_result = tf.multiply(a, b) # Multiplication

print("Sum of Tensors",sum_result)
print("Difference of tensors",diff_result)
print("Quotient of Tensor",quot_result)
print("Product of tensors ",prod_result)

Sum of Tensors tf.Tensor([5 5 5], shape=(3,), dtype=int32)
Difference of tensors tf.Tensor([1 1 1], shape=(3,), dtype=int32)
Quotient of Tensor tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float64)
Product of tensors  tf.Tensor([6 6 6], shape=(3,), dtype=int32)


In [4]:
# Element-wise operations
min_result = tf.minimum(a, b)
max_result = tf.maximum(a, b)
abs_result = tf.abs(a)
  

print("Minimum:", min_result)
print("Maximum:", max_result)
print("Absolute value:", abs_result)


Minimum: tf.Tensor([2 2 2], shape=(3,), dtype=int32)
Maximum: tf.Tensor([3 3 3], shape=(3,), dtype=int32)
Absolute value: tf.Tensor([3 3 3], shape=(3,), dtype=int32)
