In [1]:
import tensorflow as tf

# Create a scalar string tensor
scalar_string_tensor = tf.constant("Hello, TensorFlow!")
print(scalar_string_tensor)

# Create a vector of strings tensor
vector_string_tensor = tf.constant(["Hello", "TensorFlow", "World"])
print(vector_string_tensor)

# Create a 2D matrix of strings tensor
matrix_string_tensor = tf.constant([["Hello", "World"], ["TensorFlow", "Rocks!"]])
print(matrix_string_tensor)

tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)
tf.Tensor([b'Hello' b'TensorFlow' b'World'], shape=(3,), dtype=string)
tf.Tensor(
[[b'Hello' b'World']
 [b'TensorFlow' b'Rocks!']], shape=(2, 2), dtype=string)


In [2]:
str1 = tf.constant("Hello")
str2 = tf.constant("World")
result = tf.strings.join([str1, str2], separator=" ")
print(result.numpy())

b'Hello World'


In [3]:
x = tf.constant("hello")

print(x.numpy())
x.numpy().decode("utf-8")

b'hello'


'hello'

In [4]:
text = "hello"

encoded = text.encode("utf-8")

print(encoded)

b'hello'


In [5]:
decoded = encoded.decode("utf-8")

print(decoded)

hello


In [6]:
x = tf.constant("😊")
tf.strings.length(x)
tf.strings.length(x, unit="UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
x = tf.constant(["Hello", "TensorFlow", "AI"])

tf.strings.length(x)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 10,  2], dtype=int32)>

In [8]:
tf.strings.join(
    ["Hello", "World"]
)

<tf.Tensor: shape=(), dtype=string, numpy=b'HelloWorld'>

In [9]:
tf.strings.join(
    ["Hello", "World"],
    separator=" "
)

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [10]:
words = tf.constant([
    "Deep",
    "Learning",
    "is",
    "fun"
])

In [11]:
sentence = tf.strings.join(
    words,
    separator=" "
)

In [12]:
text = tf.constant(
    "TensorFlow is powerful"
)

words = tf.strings.split(text)

print(words)

tf.Tensor([b'TensorFlow' b'is' b'powerful'], shape=(3,), dtype=string)


In [13]:
x = tf.constant("   hello   ")

In [14]:
tf.strings.strip(x)

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [15]:
x = tf.constant(["cat", "dog", "cat"])

tf.equal(x, "cat")

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True, False,  True])>

In [16]:
name = tf.constant("Anzar")
age = tf.constant(25)

result = tf.strings.format(
    "Name: {}, Age: {}",
    (name, age)
)

In [17]:
result

<tf.Tensor: shape=(), dtype=string, numpy=b'Name: "Anzar", Age: 25'>