In [1]:
import tensorflow as tf

In [3]:
var = tf.Variable([34,5,6])

In [4]:
var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([34,  5,  6], dtype=int32)>

### Assigning or modifying the elements in the variable

* assign() method to modify the variable.
* Variable.assign_add() and Variable.assign_sub()

In [7]:
var = var[0].assign(5)
var

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([5, 5, 6], dtype=int32)>

In [8]:
var= var.assign_add([3,4,5])
var.numpy()

array([ 8,  9, 11], dtype=int32)

In [11]:
x = tf.Variable(
    10,
    dtype=tf.float32
)
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>

In [12]:
W = tf.Variable(
    tf.random.normal((3, 2))
)

b = tf.Variable(
    tf.zeros(2)
)

In [15]:
W

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.12839228, -1.1121371 ],
       [ 0.35550213, -1.344099  ],
       [-0.7327684 , -0.7301014 ]], dtype=float32)>

In [16]:
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [17]:
x = tf.Variable([10, 20, 30, 40])

x[1:3].assign([200, 300])

print(x)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 10, 200, 300,  40], dtype=int32)>


### Important property: trainable

In [18]:
w = tf.Variable(
    10.0,
    trainable=True
)

In [19]:
x = tf.Variable(
    10.0,
    trainable=False
)

tf.zeros
tf.ones
tf.random.normal
tf.random.uniform

In [3]:
import tensorflow as tf
w = tf.Variable(
    tf.zeros((3, 3))
)

In [21]:
w

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [6]:
import tensorflow as tf

x = tf.Variable([10, 20, 30])

new_x = tf.concat(
    [x, [40,56,78]],
    axis=0
)

print(new_x.numpy())

[10 20 30 40 56 78]
