In [1]:
import pandas as pd

In [2]:
import tensorflow as tf


In [7]:
cons = tf.constant(34)

In [8]:
cons

<tf.Tensor: shape=(), dtype=int32, numpy=34>

In [9]:
print(cons.numpy())

34


In [12]:
vec = tf.constant([1,2,3,4,5,66])
vec

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5, 66], dtype=int32)>

In [13]:
print(vec.numpy())

[ 1  2  3  4  5 66]


In [1]:
# d3_matrix = tf.constant()

In [16]:
vec = tf.constant([23,45,6,77,88,3,22,24,52,3])

In [17]:
index = [1,2,3,5]
print()

VARIABLES

In [18]:
var = tf.Variable([54,566,778,22,445,6])
print(var.numpy())

[ 54 566 778  22 445   6]


#to assign a new value to the array or updation

In [19]:
var[0].assign(111)
print(var.numpy())

[111 566 778  22 445   6]


subtraction operator 
((t2 will be first and t1 will be second ))

In [22]:
t1 = tf.Variable([1,2,3,4])
t2 = tf.Variable([4,5,6,7])
t1.assign_sub(t2).numpy()

array([-3, -3, -3, -3], dtype=int32)

In [ ]:
import tensorflow as tf
x =tf.Variable([[10,20,30]])
print(x.numpy())
newx = tf.concat(
    [x,[[30,40,50]]],
    axis = 0

    #axis is here for row and column
    #axis = 0 -> concatenation through row
    #axis = 1 -> concatenation through column

)
print(newx.numpy())

[[10 20 30]]
[[10 20 30]
 [30 40 50]]
